const adminTypes = {
    ADD_USER_SUCCESS : 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE : 'ADD_USER_FAILURE',
    ADD_USER_FAILURE_MSG: 'ADD_USER_FAILURE_MSG',
    RESET_AUTH_FORM: 'RESET_AUTH_FORM',
    ADMIN_DATA: 'ADMIN_DATA'
}

export default adminTypes